let data = [
{"id":1,"username":"rlowden0","content":"Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.","color":"#6fb1af","buzzword":"Versatile","avatar":"https://robohash.org/voluptasquasea.jpg?size=50x50&set=set1"},
{"id":2,"username":"eladdle1","content":"Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.","color":"#220b50","buzzword":"intermediate","avatar":"https://robohash.org/suscipiteosexercitationem.png?size=50x50&set=set1"},
{"id":3,"username":"fbamlett2","content":"Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.","color":"#03c72c","buzzword":"Polarised","avatar":"https://robohash.org/aperiamvoluptatibusnon.jpg?size=50x50&set=set1"},
{"id":4,"username":"rkubin3","content":"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.","color":"#b32020","buzzword":"complexity","avatar":"https://robohash.org/undedoloresdignissimos.png?size=50x50&set=set1"},
{"id":5,"username":"thegges4","content":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.","color":"#526f48","buzzword":"protocol","avatar":"https://robohash.org/consequaturrepellendusharum.png?size=50x50&set=set1"},
{"id":6,"username":"tchapelhow5","content":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.","color":"#3c42e8","buzzword":"Future-proofed","avatar":"https://robohash.org/blanditiisetut.jpg?size=50x50&set=set1"},
{"id":7,"username":"reighteen6","content":"Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.","color":"#ae6b79","buzzword":"Object-based","avatar":"https://robohash.org/teneturlaborenisi.jpg?size=50x50&set=set1"},
{"id":8,"username":"cgeer7","content":"Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.","color":"#39dbd2","buzzword":"monitoring","avatar":"https://robohash.org/etdebitisenim.png?size=50x50&set=set1"},
{"id":9,"username":"crottenbury8","content":"In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.","color":"#b8560a","buzzword":"discrete","avatar":"https://robohash.org/dolorumquisconsequatur.bmp?size=50x50&set=set1"},
{"id":10,"username":"csabatier9","content":"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.","color":"#66078e","buzzword":"function","avatar":"https://robohash.org/tenetureligendiaspernatur.png?size=50x50&set=set1"},
{"id":11,"username":"hyarnleya","content":"In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.","color":"#c566c0","buzzword":"Business-focused","avatar":"https://robohash.org/inciduntmolestiaedolore.png?size=50x50&set=set1"},
{"id":12,"username":"dpentonyb","content":"Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","color":"#009236","buzzword":"model","avatar":"https://robohash.org/sitquaeratnumquam.jpg?size=50x50&set=set1"},
{"id":13,"username":"asambalsc","content":"Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.","color":"#cecb06","buzzword":"Configurable","avatar":"https://robohash.org/quaeratteneturcorporis.bmp?size=50x50&set=set1"},
{"id":14,"username":"vmacafeed","content":"Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.","color":"#ae9334","buzzword":"matrix","avatar":"https://robohash.org/doloribusmolestiasquasi.jpg?size=50x50&set=set1"},
{"id":15,"username":"wmcsaule","content":"Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.","color":"#c0a313","buzzword":"orchestration","avatar":"https://robohash.org/voluptatemilloest.jpg?size=50x50&set=set1"},
{"id":16,"username":"lkraftf","content":"Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.","color":"#fd69d7","buzzword":"real-time","avatar":"https://robohash.org/nesciuntaspernaturmodi.jpg?size=50x50&set=set1"},
{"id":17,"username":"ahulkeg","content":"Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.","color":"#56495e","buzzword":"Fully-configurable","avatar":"https://robohash.org/rerumutfacere.jpg?size=50x50&set=set1"},
{"id":18,"username":"jfeldharkerh","content":"Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","color":"#55e647","buzzword":"modular","avatar":"https://robohash.org/dolorumautemnecessitatibus.png?size=50x50&set=set1"},
{"id":19,"username":"hjacobsoni","content":"In congue. Etiam justo. Etiam pretium iaculis justo.","color":"#af65ea","buzzword":"support","avatar":"https://robohash.org/etconsequaturfacere.bmp?size=50x50&set=set1"},
{"id":20,"username":"ttalloej","content":"Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.","color":"#917ba3","buzzword":"high-level","avatar":"https://robohash.org/quibusdambeataeet.jpg?size=50x50&set=set1"},
{"id":21,"username":"cmarksonk","content":"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.","color":"#b55c05","buzzword":"Exclusive","avatar":"https://robohash.org/suntquiasaepe.jpg?size=50x50&set=set1"},
{"id":22,"username":"rkibardl","content":"Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.","color":"#3dc336","buzzword":"Inverse","avatar":"https://robohash.org/nihilsintaccusamus.png?size=50x50&set=set1"},
{"id":23,"username":"acrenshawm","content":"Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.","color":"#e8acd5","buzzword":"even-keeled","avatar":"https://robohash.org/doloremdelectuset.jpg?size=50x50&set=set1"},
{"id":24,"username":"cwoodburnn","content":"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.","color":"#a13a1d","buzzword":"Customer-focused","avatar":"https://robohash.org/corruptifugitid.bmp?size=50x50&set=set1"},
{"id":25,"username":"btrittono","content":"Phasellus in felis. Donec semper sapien a libero. Nam dui.","color":"#600fa7","buzzword":"Face to face","avatar":"https://robohash.org/utquorerum.jpg?size=50x50&set=set1"},
{"id":26,"username":"ncoyp","content":"Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.","color":"#8f578c","buzzword":"Phased","avatar":"https://robohash.org/etenimvoluptate.jpg?size=50x50&set=set1"},
{"id":27,"username":"cskellenq","content":"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.","color":"#83879e","buzzword":"hierarchy","avatar":"https://robohash.org/ettemporeconsequuntur.bmp?size=50x50&set=set1"},
{"id":28,"username":"mbraybrooker","content":"Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.","color":"#ed2a01","buzzword":"concept","avatar":"https://robohash.org/asperioresautomnis.png?size=50x50&set=set1"},
{"id":29,"username":"ggildersleeves","content":"Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.","color":"#8817ec","buzzword":"Monitored","avatar":"https://robohash.org/etnonalias.jpg?size=50x50&set=set1"},
{"id":30,"username":"gdakhovt","content":"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.","color":"#6dc72b","buzzword":"Intuitive","avatar":"https://robohash.org/animiquoet.png?size=50x50&set=set1"},
{"id":31,"username":"emelluishu","content":"Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.","color":"#c60131","buzzword":"Fundamental","avatar":"https://robohash.org/vitaeenimquam.bmp?size=50x50&set=set1"},
{"id":32,"username":"cnockv","content":"Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.","color":"#642247","buzzword":"Right-sized","avatar":"https://robohash.org/voluptasnecessitatibussaepe.bmp?size=50x50&set=set1"},
{"id":33,"username":"rmanilovew","content":"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.","color":"#ec1aa1","buzzword":"Exclusive","avatar":"https://robohash.org/eosmolestiasculpa.bmp?size=50x50&set=set1"},
{"id":34,"username":"kbaylyx","content":"Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.","color":"#a727a7","buzzword":"throughput","avatar":"https://robohash.org/aspernaturtotamnesciunt.bmp?size=50x50&set=set1"},
{"id":35,"username":"mrichmonty","content":"In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.","color":"#449833","buzzword":"Seamless","avatar":"https://robohash.org/etmolestiaeneque.jpg?size=50x50&set=set1"},
{"id":36,"username":"dheaslipz","content":"Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.","color":"#829011","buzzword":"info-mediaries","avatar":"https://robohash.org/quaesedsed.png?size=50x50&set=set1"},
{"id":37,"username":"aroskams10","content":"Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.","color":"#42ff3c","buzzword":"incremental","avatar":"https://robohash.org/sedquiducimus.png?size=50x50&set=set1"},
{"id":38,"username":"mdaynter11","content":"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.","color":"#c65b15","buzzword":"radical","avatar":"https://robohash.org/utfacereaperiam.bmp?size=50x50&set=set1"},
{"id":39,"username":"aredhole12","content":"Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.","color":"#9e34a0","buzzword":"systemic","avatar":"https://robohash.org/inquiaquia.png?size=50x50&set=set1"},
{"id":40,"username":"soldfield13","content":"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.","color":"#90dfa9","buzzword":"real-time","avatar":"https://robohash.org/doloremqueveltotam.jpg?size=50x50&set=set1"},
{"id":41,"username":"lmaytom14","content":"Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.","color":"#7558e9","buzzword":"local","avatar":"https://robohash.org/voluptatemomnisquae.png?size=50x50&set=set1"},
{"id":42,"username":"yglaysher15","content":"Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.","color":"#d24dc4","buzzword":"Pre-emptive","avatar":"https://robohash.org/rerumquieaque.bmp?size=50x50&set=set1"},
{"id":43,"username":"lbarron16","content":"Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","color":"#f6e068","buzzword":"full-range","avatar":"https://robohash.org/culpanumquameos.png?size=50x50&set=set1"},
{"id":44,"username":"slockhurst17","content":"Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","color":"#58df0c","buzzword":"User-centric","avatar":"https://robohash.org/doloribusnoneius.png?size=50x50&set=set1"},
{"id":45,"username":"emalinson18","content":"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.","color":"#859531","buzzword":"function","avatar":"https://robohash.org/assumendasuntrepellendus.png?size=50x50&set=set1"},
{"id":46,"username":"cpatemore19","content":"Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.","color":"#7b8637","buzzword":"Profit-focused","avatar":"https://robohash.org/voluptasdelectussimilique.jpg?size=50x50&set=set1"},
{"id":47,"username":"everbeek1a","content":"Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.","color":"#1526c1","buzzword":"Front-line","avatar":"https://robohash.org/etnihilconsequatur.jpg?size=50x50&set=set1"},
{"id":48,"username":"vhovey1b","content":"Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.","color":"#497dee","buzzword":"analyzer","avatar":"https://robohash.org/commodiofficiisnon.png?size=50x50&set=set1"},
{"id":49,"username":"bmaharg1c","content":"Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.","color":"#aef017","buzzword":"access","avatar":"https://robohash.org/voluptatemdelectusexpedita.jpg?size=50x50&set=set1"},
{"id":50,"username":"mbracken1d","content":"Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.","color":"#68c494","buzzword":"implementation","avatar":"https://robohash.org/ipsammaximebeatae.png?size=50x50&set=set1"}
];

module.exports = {
    getData: (req, res) => {

        //SERVER - REST (queries): student can create a RESTful API (queries)
        if (req.query.buzzword) {
            let filtered = data.filter(data => data.buzzword.toLowerCase().includes(req.query.buzzword.toLowerCase()) || data.content.toLowerCase().includes(req.query.buzzword.toLowerCase()));
            res.status(200).send(filtered);
        }
        else {
            res.status(200).send(data);
        }
    },

    login: (req, res) => {
        let {username} = req.body;
        req.session.user = username;
        res.status(200).send('User Logged In');
    },

    logout: (req, res) => {
        req.session.destroy();
        res.status(200).send('User Logged Out');
    }
}